### ISSUE TITLE
An error is reported during compilation in the WSL environment

### ISSUE THREAD

**Issue by try-agaaain** [4paradigm/OpenMLDB#2692]
**Bug Description**

Refer to the documentation: https://openmldb.ai/docs/zh/main/deploy/compile.html#docker, I want to finish compiling OpenMLDB in WSL (ubuntu 22.04), but I got the following error:

```shell
[ 54%] Linking CXX executable ../../../../bin/toydb
/usr/bin/ld: ../../../../../.deps/usr/lib/libbrpc.a(mutex.cpp.o): in function `bthread::init_sys_mutex_lock()':
/__w/hybridsql-asserts/hybridsql-asserts/deps/build/src/brpc/src/bthread/mutex.cpp:411: undefined reference to `_dl_sym'
/usr/bin/ld: /__w/hybridsql-asserts/hybridsql-asserts/deps/build/src/brpc/src/bthread/mutex.cpp:412: undefined reference to `_dl_sym'
collect2: error: ld returned 1 exit status
gmake[3]: *** [hybridse/examples/toydb/src/CMakeFiles/toydb.dir/build.make:219: bin/toydb] Error 1
gmake[3]: Leaving directory '/home/todo/local_repo/OpenMLDB/build'
gmake[2]: *** [CMakeFiles/Makefile2:649: hybridse/examples/toydb/src/CMakeFiles/toydb.dir/all] Error 2
gmake[2]: Leaving directory '/home/todo/local_repo/OpenMLDB/build'
gmake[1]: *** [Makefile:136: all] Error 2
gmake[1]: Leaving directory '/home/todo/local_repo/OpenMLDB/build'
make: *** [Makefile:110: build] Error 2
```

**Expected Behavior**

I expect OpenMLDB to build fine in WSL (ubuntu 22.04).

**Comment by aceforeverd** [comment]
Neither WSL or ubuntu 22.04 is guaranteed to build success. 

Two advice:
- build inside hybridsql docker
- or in your environment, build third party manually: `make build BUILD_BUNDLED=ON`. Note this may not success still, due to dependency missing or something else

**Comment by vagetablechicken** [comment]
@team-317 brpc needs patch in ubuntu22.04, building third party is not helpful. How about use ubuntu 20.04? or I can upload a pre-built thirdparty for ubuntu 22.04

**Comment by try-agaaain** [comment]
Thanks, I'll try building on ubuntu20.04 first

**Comment by try-agaaain** [comment]
I tried building on WSL Ubuntu 20.04, but the process was too slow, so I built on docker and now it's successful. 😄
